import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./ui/components/sidebar";
import { Header } from "./ui/components/header";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${karla.className} bg-gray-100 flex`}>
        <Sidebar />
        <Header>
          <div className="w-full overflow-x-hidden border-t flex flex-col">
            <main className="w-full flex-grow p-6">{children}</main>
          </div>
        </Header>
      </body>
    </html>
  );
}
